/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Ponto;
import model.Quadrante;

/**
 *
 * @author yvasouza
 */
public class ViewUi extends javax.swing.JFrame {

    /**
     * Creates new form ViewUi
     */
    public ViewUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblX = new javax.swing.JTextField();
        lblY = new javax.swing.JTextField();
        btnAvaliar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        chboxQuadranteUm = new javax.swing.JCheckBox();
        chboxQuadranteDois = new javax.swing.JCheckBox();
        chboxQuadranteTres = new javax.swing.JCheckBox();
        chboxQuadranteQuatro = new javax.swing.JCheckBox();
        chboxEixoX = new javax.swing.JCheckBox();
        chboxEixoY = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        lblX.setMinimumSize(new java.awt.Dimension(100, 100));

        lblY.setToolTipText("");

        btnAvaliar.setText("Avaliar");
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });

        jLabel3.setText("Posição:");

        chboxQuadranteUm.setText("No 1º Quadrante");
        chboxQuadranteUm.setEnabled(false);
        chboxQuadranteUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxQuadranteUmActionPerformed(evt);
            }
        });

        chboxQuadranteDois.setText("No 2º Quadrante");
        chboxQuadranteDois.setActionCommand("No 2º Quadrante");
        chboxQuadranteDois.setEnabled(false);
        chboxQuadranteDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxQuadranteDoisActionPerformed(evt);
            }
        });

        chboxQuadranteTres.setText("No 3º Quadrante");
        chboxQuadranteTres.setActionCommand("No 3º Quadrante");
        chboxQuadranteTres.setEnabled(false);
        chboxQuadranteTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxQuadranteTresActionPerformed(evt);
            }
        });

        chboxQuadranteQuatro.setText("No 4º Quadrante");
        chboxQuadranteQuatro.setEnabled(false);
        chboxQuadranteQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxQuadranteQuatroActionPerformed(evt);
            }
        });

        chboxEixoX.setText("Incide sob Eixo X");
        chboxEixoX.setEnabled(false);
        chboxEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxEixoXActionPerformed(evt);
            }
        });

        chboxEixoY.setText("Incide sob Eixo Y");
        chboxEixoY.setEnabled(false);
        chboxEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxEixoYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chboxEixoY)
                    .addComponent(chboxEixoX)
                    .addComponent(chboxQuadranteQuatro)
                    .addComponent(chboxQuadranteTres)
                    .addComponent(chboxQuadranteDois)
                    .addComponent(chboxQuadranteUm)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chboxQuadranteUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chboxQuadranteDois)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chboxQuadranteTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chboxQuadranteQuatro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chboxEixoX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chboxEixoY)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblY))
                        .addGap(20, 20, 20)
                        .addComponent(btnAvaliar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chboxQuadranteUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxQuadranteUmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxQuadranteUmActionPerformed

    private void chboxQuadranteDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxQuadranteDoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxQuadranteDoisActionPerformed

    private void chboxQuadranteTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxQuadranteTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxQuadranteTresActionPerformed

    private void chboxQuadranteQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxQuadranteQuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxQuadranteQuatroActionPerformed

    private void chboxEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxEixoXActionPerformed

    private void chboxEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboxEixoYActionPerformed

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        setFalseCheckBox();
        
        int x = Integer.parseInt(lblX.getText());
        int y = Integer.parseInt(lblY.getText());
        
        Ponto ponto = new Ponto(x, y);
        
        Quadrante quadrante = ponto.identificarQuadrante();
        switch(quadrante){
            case PRIMEIRO:
               chboxQuadranteUm.setSelected(true);
               break;
            case SEGUNDO:
               chboxQuadranteDois.setSelected(true);
               break;
            case TERCEIRO:
               chboxQuadranteTres.setSelected(true);
               break;
            case QUARTO:
               chboxQuadranteQuatro.setSelected(true);
               break;
            default:
                if(ponto.estaIncidindoSobreX()){
                    chboxEixoX.setSelected(true);
                }else{
                    chboxEixoY.setSelected(true);
                }
                break;
        }
    }//GEN-LAST:event_btnAvaliarActionPerformed

    private void setFalseCheckBox(){
        chboxQuadranteUm.setSelected(false);
        chboxQuadranteDois.setSelected(false);
        chboxQuadranteTres.setSelected(false);
        chboxQuadranteQuatro.setSelected(false);
        chboxEixoX.setSelected(false);
        chboxEixoY.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JCheckBox chboxEixoX;
    private javax.swing.JCheckBox chboxEixoY;
    private javax.swing.JCheckBox chboxQuadranteDois;
    private javax.swing.JCheckBox chboxQuadranteQuatro;
    private javax.swing.JCheckBox chboxQuadranteTres;
    private javax.swing.JCheckBox chboxQuadranteUm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblX;
    private javax.swing.JTextField lblY;
    // End of variables declaration//GEN-END:variables
}
